name       : python-setuptools-rust
version    : 1.6.0
release    : 6
source     :
    # Use full git clones or pypi tarballs only. The Github release-tag-generated tarballs do not have the required metadata
    - https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-1.6.0.tar.gz : c86e734deac330597998bfbc08da45187e6b27837e23bd91eadb320732392262
homepage   : https://github.com/PyO3/setuptools-rust
license    : MIT
component  : programming.python
summary    : setuptools plugin for rust support
description: |
    Compile and distribute Python extensions written in rust as easily as if they were written in C.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools-scm
    - python-toml
    - python-typing-extensions
    - python-wheel
rundeps    :
    - cargo
    - python-semanticversion
    - python-toml
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
