name       : python-setuptools-rust
version    : 0.12.1
release    : 2
source     :
    # Use full git clones or pypi tarballs only. The Github release-tag-generated tarballs do not have the required metadata
    - https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-0.12.1.tar.gz : 647009e924f0ae439c7f3e0141a184a69ad247ecb9044c511dabde232d3d570e
homepage   : https://github.com/PyO3/setuptools-rust
license    : MIT
component  : programming.python
summary    : setuptools plugin for rust support
description: |
    Compile and distribute Python extensions written in rust as easily as if they were written in C.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools-scm
    - python-toml
    - python-wheel
rundeps    :
    - python-semanticversion
    - python-toml
    - rust
build      : |
    %python3_setup
install    : |
    %python3_install
