name       : python-setuptools-rust
version    : 1.5.2
release    : 5
source     :
    # Use full git clones or pypi tarballs only. The Github release-tag-generated tarballs do not have the required metadata
    - https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-1.5.2.tar.gz : d8daccb14dc0eae1b6b6eb3ecef79675bd37b4065369f79c35393dd5c55652c7
homepage   : https://github.com/PyO3/setuptools-rust
license    : MIT
component  : programming.python
summary    : setuptools plugin for rust support
description: |
    Compile and distribute Python extensions written in rust as easily as if they were written in C.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools-scm
    - python-toml
    - python-typing-extensions
    - python-wheel
rundeps    :
    - cargo
    - python-semanticversion
    - python-toml
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
